apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.printer.name }}-service
spec:
  type: LoadBalancer
  selector:
    app: {{ .Values.printer.name }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}